# Generated by Django 4.1 on 2022-08-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='buy_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
